### PR TITLE
Mono fixes

### PR DESCRIPTION
**Pull request by Thorium**
Ok, the real problem wasn't the SQLProvider, it was actually MySQL/MariaDB:

- MySQL is Case Insensitive in Windows.
- MySQL is Case Sensitive in Mac/Linux.

This is due to file system differences. Anyways I wanted to be able to use the same F# source code using MySQL from Windows and Linux and now it is possible. I didn't test if LOWER-conversion would somehow causing not-hitting-the-table-index (while I know that this would be the case with Oracle) but the conversion is done by compile-time queries to system tables; and who would use 10000 column system tables with the MySQL so it probably doesn't matter. The table names shown to the user are still in the right case.

Also fixed the delete command parameter name.

This will fix issue fsprojects/SQLProvider#140

### CODE REVIEW

**Comment by Thorium** [comment]
Should case sensitivity be actually one of the static parameters to the provider?
E.g. You can set the MS-SQL database collation to be to CI (insensitive) or CS (sensitive).

**Comment by Thorium** [comment]
Ping @pezipink, if I make some PR to the SQLProvider, should I do it to Colin's branch (to avoid merge conflicts) or directly to FsProject?

**Comment by colinbull** [comment]
This should go directly to fsprojects. I'll pick up the changes, when we
finally get this thing to a branch on fsprojects.

**Comment by Thorium** [comment]
I'll reject this one as the fsproject has now better PR. I can help with the merge if there is any issues.

**Pull request closed without merging**
